<?php

/**
 * @file
 * Functions to support theming in the Seven theme.
 */

use Drupal\Component\Utility\Xss;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_page().
 */
function monoset_preprocess_page(&$variables) {
  // Load this library only on front page.
  if ($variables['is_front']) {
    $variables['#attached']['library'][] = 'monoset/front-page';
  }
}